R2dia=40;
R2complex=38;
R2sp=200;
R2a=50;
R2b=R2dia+R2complex+R2sp;
pA=0;
pB=1-pA;
kex=1000;
pi=3.14;
nuA=100;
nuB=160;
nu=0:260;
lambdaA=R2a+pB*kex-2*pi*1i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*1i*(nuB-nu);
G=1i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
maxPara100=max(imag(G))
figure
hold on
plot(nu,imag(G),'r')
R2b=R2dia+R2complex;
lambdaA=R2a+pB*kex-2*pi*1i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*1i*(nuB-nu);
G=1i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
maxDia100=max(imag(G))
ratio100=maxPara100/maxDia100
plot(nu,imag(G),'r')
R2b=R2dia+R2complex+R2sp;
pA=0.33;
pB=1-pA;
lambdaA=R2a+pB*kex-2*pi*i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*i*(nuB-nu);
G=i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
%figure
plot(nu,imag(G),'b')
pA=0.66;
pB=1-pA;
lambdaA=R2a+pB*kex-2*pi*i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*i*(nuB-nu);
G=i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
%figure
maxPara33=max(imag(G))
plot(nu,imag(G),'r')
R2b=R2dia+R2complex;
lambdaA=R2a+pB*kex-2*pi*i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*i*(nuB-nu);
G=i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
maxDia33=max(imag(G))
ratio33=maxPara33/maxDia33
plot(nu,imag(G),'r')

R2b=R2dia+R2complex+R2sp;
pA=1;
pB=1-pA;
lambdaA=R2a+pB*kex-2*pi*i*(nuA-nu);
lambdaB=R2b+pA*kex-2*pi*i*(nuB-nu);
G=i*(lambdaA*pB+lambdaB*pA+2*pA*pB*kex)./(lambdaA.*lambdaB-pA*pB*kex*kex);
%figure
plot(nu,imag(G))